"""
Django settings for sockets project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# ==================================================Base directory==================================================
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent.parent

#==================================================Environment====================================================
load_dotenv()

envPath = os.path.join(BASE_DIR, 'variables.env')
load_dotenv(dotenv_path=envPath)

# ==================================================Secret key==================================================
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# ==================================================Application definition==================================================
INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'web_socket',
]

# ==================================================App configuration==================================================
ROOT_URLCONF = 'sockets.urls'
WSGI_APPLICATION = 'sockets.wsgi.application'
ASGI_APPLICATION = 'sockets.asgi.application'

# ==================================================Internationalization==================================================
USE_I18N = True

USE_L10N = False

USE_TZ = True

# ==================================================Channel Configuration==================================================
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': "channels.layers.InMemoryChannelLayer"
        }
    }


# ==================================================Template Configuration==================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
