# Generated by Django 3.2.8 on 2023-02-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banner_db',
        ),
        migrations.AlterModelTable(
            name='businessschedule',
            table='business_schedule',
        ),
    ]
