# Generated by Django 3.2.8 on 2023-02-22 13:24

from django.db import migrations, models
import global_methods


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0002_auto_20230222_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='story_videos/', validators=[global_methods.file_size]),
        ),
    ]
