# Generated by Django 3.2.8 on 2023-02-24 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0003_auto_20230222_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('disc', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(upload_to='product_images/')),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.subcategories')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'i_user')},
            },
        ),
    ]
