# Generated by Django 3.2.8 on 2023-02-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0006_redemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
