# Generated by Django 3.2.8 on 2023-02-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0008_auto_20230228_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
