# Generated by Django 3.2.8 on 2023-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0013_alter_business_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_claimed',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1),
        ),
        migrations.AddField(
            model_name='business',
            name='place_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
