# Generated by Django 3.2.8 on 2023-03-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0014_auto_20230306_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='i_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
