# Generated by Django 3.2.8 on 2023-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0015_alter_business_i_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
