# Generated by Django 3.2.8 on 2023-03-09 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0017_popularsearch_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('disc', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(upload_to='product_images/')),
                ('content_type', models.IntegerField(choices=[(1, 'Product'), (2, 'Service'), (3, 'Restaurant'), (4, 'Health Care')], default=1)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.subcategories')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contents',
                'db_table': 'contents',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'i_user')},
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='i_subcatagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.subcategories'),
        ),
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('MIDDLE', 'Middle'), ('BOTTOM', 'Bottom'), ('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='sub_catagory_type',
            field=models.CharField(blank=True, choices=[('SUB_CATAGORY', 'Sub Catagory'), ('IMAGE', 'Image')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
