# Generated by Django 3.2.8 on 2023-03-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0021_auto_20230309_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='i_category',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='i_subcategory',
            field=models.ManyToManyField(to='hubur_apis.SubCategories'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
