# Generated by Django 3.2.8 on 2023-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0025_auto_20230313_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(blank=True, choices=[('TOP', 'Top')], max_length=7, null=True),
        ),
    ]
