# Generated by Django 3.2.8 on 2023-03-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0026_alter_banner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('MIDDLE', 'Middle')], max_length=7, null=True),
        ),
    ]
