# Generated by Django 3.2.8 on 2023-03-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0029_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='Users',
        ),
    ]
