# Generated by Django 3.2.8 on 2023-03-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0030_auto_20230320_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Businesses'},
        ),
    ]
