# Generated by Django 3.2.8 on 2023-03-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0031_alter_business_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='i_sub_category',
        ),
        migrations.AddField(
            model_name='content',
            name='i_sub_category',
            field=models.ManyToManyField(to='hubur_apis.SubCategories'),
        ),
    ]
