# Generated by Django 3.2.8 on 2023-03-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0032_auto_20230320_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularsearch',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popularsearch',
            name='type_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
