# Generated by Django 3.2.8 on 2023-03-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0033_auto_20230320_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemption',
            name='i_business',
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='i_sub_categories',
        ),
        migrations.AddField(
            model_name='content',
            name='i_business',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redemption',
            name='i_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrendingDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_business', models.ManyToManyField(related_name='trending_discount_business', to='hubur_apis.Business')),
            ],
            options={
                'verbose_name_plural': 'Trending Discount',
                'db_table': 'trending_discount_db',
                'ordering': ['-created_at'],
            },
        ),
    ]
