# Generated by Django 3.2.8 on 2023-03-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0034_auto_20230325_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularsearch',
            name='catagory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
