# Generated by Django 3.2.8 on 2023-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0035_popularsearch_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='sub_catagory_type',
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(blank=True, choices=[(1, 'Top'), (2, 'Middle'), (3, 'After Have You Been There'), (4, 'Before My Favourites')], max_length=7, null=True),
        ),
    ]
