# Generated by Django 3.2.8 on 2023-03-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0038_alter_banner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingdiscount',
            name='image',
            field=models.ImageField(upload_to='category_images/'),
        ),
    ]
