# Generated by Django 3.2.8 on 2023-04-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0039_alter_trendingdiscount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='type',
            field=models.IntegerField(choices=[(1, 'Business_Catalog'), (2, 'Product'), (3, 'Service')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='multi_images/'),
        ),
    ]
