# Generated by Django 3.2.8 on 2023-04-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0040_auto_20230403_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='i_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='other_images/'),
        ),
    ]
