# Generated by Django 3.2.8 on 2023-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0041_auto_20230404_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo_pic',
            field=models.ImageField(default='business_images/bag.png', upload_to='business_images/'),
        ),
    ]
