# Generated by Django 3.2.8 on 2023-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0045_myfavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
