# Generated by Django 3.2.8 on 2023-04-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0051_contactus_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='country_code',
        ),
    ]
