# Generated by Django 3.2.8 on 2023-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0054_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
