# Generated by Django 3.2.19 on 2023-05-06 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0059_auto_20230502_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularsearch',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='popularsearch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='popularsearch',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='popularsearch',
            name='url',
        ),
        migrations.AddField(
            model_name='popularsearch',
            name='i_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.brand'),
        ),
        migrations.AddField(
            model_name='popularsearch',
            name='i_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business'),
        ),
        migrations.AddField(
            model_name='popularsearch',
            name='i_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content'),
        ),
        migrations.CreateModel(
            name='MyBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'My Bookmark',
                'db_table': 'my_bookmark_db',
                'ordering': ['-created_at'],
            },
        ),
    ]
