# Generated by Django 3.2.8 on 2023-05-08 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0060_auto_20230506_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.IntegerField(choices=[(1, 'Hourly'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('discount', models.IntegerField(choices=[(1, 'Percentage'), (2, 'Fixed')], default=1)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_expiry', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_business', models.ManyToManyField(to='hubur_apis.Business')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'db_table': 'offer_db',
                'ordering': ['-created_at'],
            },
        ),
    ]
