# Generated by Django 3.2.8 on 2023-05-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0062_auto_20230511_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
