# Generated by Django 3.2.8 on 2023-05-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0064_banner_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='founded_country',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='founded_year',
        ),
    ]
