# Generated by Django 3.2.8 on 2023-05-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0065_auto_20230511_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='discount',
            new_name='discount_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='picture',
        ),
        migrations.AddField(
            model_name='images',
            name='i_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content'),
        ),
        migrations.AddField(
            model_name='offers',
            name='discount_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.IntegerField(choices=[(1, 'Product'), (2, 'Service'), (3, 'Menu'), (4, 'Health Care')], default=1),
        ),
        migrations.AlterField(
            model_name='images',
            name='type',
            field=models.IntegerField(choices=[(1, 'Business_Catalog'), (2, 'Product'), (3, 'Service'), (4, 'Menu'), (5, 'Health Care')]),
        ),
    ]
