# Generated by Django 3.2.8 on 2023-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0067_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
