# Generated by Django 3.2.8 on 2023-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0068_attributes_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='value',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributes',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
