# Generated by Django 3.2.8 on 2023-05-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0069_auto_20230512_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='i_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content'),
            preserve_default=False,
        ),
    ]
