# Generated by Django 3.2.8 on 2023-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0070_attributes_i_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='disc',
        ),
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
