# Generated by Django 3.2.8 on 2023-05-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0072_auto_20230518_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='i_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.brand'),
        ),
    ]
