# Generated by Django 3.2.8 on 2023-05-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0073_content_i_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='i_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='i_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content'),
        ),
    ]
