# Generated by Django 3.2.8 on 2023-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0074_auto_20230522_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='i_business',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='i_content',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='value',
        ),
        migrations.AddField(
            model_name='business',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='business',
            name='i_attributes',
            field=models.ManyToManyField(blank=True, null=True, to='hubur_apis.Attributes'),
        ),
        migrations.AddField(
            model_name='content',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='sku',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
