# Generated by Django 3.2.8 on 2023-05-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0075_auto_20230522_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfavourite',
            name='i_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, 'Top'), (2, 'Middle'), (3, 'After Have You Been There'), (4, 'Before My Favourites'), (5, 'Catagory Page'), (6, 'Bottom')]),
        ),
        migrations.AlterField(
            model_name='myfavourite',
            name='i_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hourly'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly'), (5, 'Hot')], default=1),
        ),
        migrations.CreateModel(
            name='SavedOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business')),
                ('i_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Offers',
                'db_table': 'saved_offer_db',
                'ordering': ['-created_at'],
            },
        ),
    ]
