# Generated by Django 3.2.8 on 2023-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0076_auto_20230523_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
