# Generated by Django 3.2.8 on 2023-05-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0077_alter_content_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
