# Generated by Django 3.2.8 on 2023-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0078_alter_content_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount_price',
            field=models.IntegerField(),
        ),
    ]
