# Generated by Django 3.2.8 on 2023-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0079_alter_offers_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
