# Generated by Django 3.2.8 on 2023-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0080_alter_offers_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='type',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=1),
        ),
    ]
