# Generated by Django 3.2.8 on 2023-05-25 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0081_alter_offers_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=225)),
                ('rate', models.FloatField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business')),
                ('i_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'review_db',
                'ordering': ['-created_at'],
            },
        ),
    ]
