# Generated by Django 3.2.8 on 2023-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0085_alter_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content'),
        ),
    ]
