# Generated by Django 3.2.8 on 2023-05-31 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0087_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Checkin'), (2, 'Redemption'), (3, 'Story')], default=1)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Reward Points',
                'db_table': 'reward_points_db',
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('i_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business')),
                ('i_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content')),
                ('i_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.rewardpoints')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Reward',
                'db_table': 'user_reward_db',
                'ordering': ['-created_at'],
            },
        ),
    ]
