# Generated by Django 3.2.8 on 2023-06-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0089_alter_offers_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
