# Generated by Django 3.2.8 on 2023-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0090_auto_20230602_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze')], default=1)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Levels',
                'db_table': 'level_db',
            },
        ),
        migrations.AlterField(
            model_name='rewardpoints',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Checkin'), (2, 'Redemption'), (3, 'Story'), (4, 'Vote')], default=1),
        ),
    ]
