# Generated by Django 3.2.8 on 2023-06-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0091_auto_20230602_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friends',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='hubur_apis.userprofile'),
            preserve_default=False,
        ),
    ]
