# Generated by Django 3.2.8 on 2023-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0094_useronlinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Redeem'), (2, 'Follow/Unfollow'), (3, 'Message'), (4, 'Friend Story'), (5, 'Saved Item Expiry Day'), (6, 'Vendor Created Deal')], null=True),
        ),
    ]
