# Generated by Django 3.2.8 on 2023-06-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0095_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Chats'},
        ),
    ]
