# Generated by Django 3.2.8 on 2023-06-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0096_alter_chat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
