# Generated by Django 3.2.8 on 2023-06-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0097_auto_20230626_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronlinestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
