# Generated by Django 3.2.8 on 2023-06-27 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0098_useronlinestatus_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_on_whatsapp', models.BooleanField(default=True)),
                ('promotional_messages', models.BooleanField(default=True)),
                ('promotional_email', models.BooleanField(default=True)),
                ('all_notifications', models.BooleanField(default=True)),
                ('new_offer', models.BooleanField(default=True)),
                ('offer_expire', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_settings_db',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Apple Token',
                'db_table': 'apple_token_db',
                'ordering': ['-created_at'],
            },
        ),
    ]
