# Generated by Django 3.2.8 on 2023-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0099_appletoken_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lang_code',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'Arabic')], default=1),
        ),
    ]
