# Generated by Django 3.2.8 on 2023-07-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0100_userprofile_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
