# Generated by Django 3.2.8 on 2023-07-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0101_category_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
