# Generated by Django 3.2.8 on 2023-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0102_subcategories_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
