# Generated by Django 3.2.8 on 2023-07-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0104_auto_20230712_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='about_us_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='disclaimer_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='privacy_policy_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='terms_condition_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, 'Top'), (2, 'Middle'), (3, 'After Have You Been There'), (4, 'Before My Favourites'), (5, 'Category Page'), (6, 'Bottom')]),
        ),
    ]
