# Generated by Django 3.2.8 on 2023-07-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0105_auto_20230713_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Redeem'), (2, 'Follow/Unfollow'), (3, 'Message'), (4, 'Friend Story'), (5, 'Saved Item Expiry Day'), (6, 'Vendor Created Deal'), (7, 'Avail Offer')], null=True),
        ),
    ]
