# Generated by Django 3.2.8 on 2023-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0106_auto_20230713_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
