# Generated by Django 3.2.8 on 2023-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0107_auto_20230713_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='offers',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
