# Generated by Django 3.2.8 on 2023-07-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0108_auto_20230713_1938'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='business',
            index_together={('is_active', 'is_featured')},
        ),
    ]
