# Generated by Django 3.2.8 on 2023-07-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0109_alter_business_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterIndexTogether(
            name='business',
            index_together=set(),
        ),
    ]
