# Generated by Django 3.2.8 on 2023-07-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0110_auto_20230713_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
