# Generated by Django 3.2.8 on 2023-07-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0111_auto_20230714_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='language',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'العربية')], default=1),
            preserve_default=False,
        ),
    ]
