# Generated by Django 3.2.8 on 2023-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0112_banner_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
