# Generated by Django 3.2.8 on 2023-07-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0113_content_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='name_ar',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
