# Generated by Django 3.2.8 on 2023-07-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0114_offers_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description_ar',
            field=models.TextField(null=True),
        ),
    ]
