# Generated by Django 3.2.8 on 2023-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0116_auto_20230721_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rewardpoints',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Check-In'), (2, 'Redemption'), (3, 'Story'), (4, 'Vote')], default=1),
        ),
    ]
