# Generated by Django 3.2.8 on 2023-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0117_auto_20230721_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ar',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
