# Generated by Django 3.2.8 on 2023-07-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0118_auto_20230721_2038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
    ]
