# Generated by Django 3.2.8 on 2023-07-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0120_auto_20230726_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssubscription',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='feature_name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
