# Generated by Django 3.2.8 on 2023-07-26 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0121_auto_20230726_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssubscription',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Business Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionfeature',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Subscription Features'},
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='businesssubscription',
            table='business_subscription_db',
        ),
        migrations.AlterModelTable(
            name='subscriptionfeature',
            table='subscription_feature_db',
        ),
    ]
