# Generated by Django 3.2.8 on 2023-07-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0122_auto_20230726_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
