# Generated by Django 3.2.8 on 2023-07-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0123_alter_businesssubscription_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(null=True)),
                ('duration_months', models.PositiveIntegerField(default=1, max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_type', models.IntegerField(choices=[(1, 'Free'), (2, 'Monthly'), (3, 'Yearly')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscription_db',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='hubur_apis.subscription'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.subscription'),
        ),
        migrations.DeleteModel(
            name='BusinessSubscription',
        ),
    ]
