# Generated by Django 3.2.8 on 2023-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0126_alter_userprofile_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'db_table': 'tags_db',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='i_tags',
            field=models.ManyToManyField(blank=True, null=True, to='hubur_apis.Tags'),
        ),
        migrations.AddField(
            model_name='content',
            name='i_tags',
            field=models.ManyToManyField(blank=True, null=True, to='hubur_apis.Tags'),
        ),
    ]
