# Generated by Django 3.2.8 on 2023-08-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0127_auto_20230727_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='i_tags',
        ),
        migrations.RemoveField(
            model_name='content',
            name='i_tags',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='name_ar',
        ),
        migrations.AddField(
            model_name='tags',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business'),
        ),
        migrations.AddField(
            model_name='tags',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.content'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
