# Generated by Django 3.2.8 on 2023-08-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubur_apis', '0128_auto_20230804_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, 'Top'), (2, 'Middle'), (3, 'After Have You Been There'), (4, 'Before My Favourites'), (5, 'Category Page'), (6, 'Bottom'), (7, 'Top Hot'), (8, 'Middle Hot')]),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('title_ar', models.CharField(max_length=30, null=True)),
                ('desc', models.TextField(max_length=100)),
                ('desc_ar', models.TextField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hubur_apis.business')),
            ],
            options={
                'verbose_name_plural': 'Campaign',
                'db_table': 'campaign_db',
                'ordering': ['-created_at'],
            },
        ),
    ]
